spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

#  security:
#    user:
#      name: user
#      password: pass
#      roles:
#        - USER
#        - ADMIN

springdoc:

  swagger-ui:
    path: /swagger
